language: node_js
node_js:
  - "8"
script:
  - echo "Deploy!!"
  - cd functions && npm install && cd -
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy bogdan-blog --token $FIREBASE_TOKEN
